# Generated by Django 5.2.8 on 2025-12-02 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
